docs/src/markdown/about/changelog.md, soupsieve/__meta__.py, soupsieve/css_parser.py, tests/test_level1.py, tests/test_level2.py, tests/test_level4.py, tests/test_soupsieve.py
=> No implementation error on supported pseudo and better ident patterns

docs/src/markdown/selectors.md, soupsieve/css_parser.py, tests/test_level4.py
=> Add read-write/read-only support

appveyor.yml, docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/selectors.md, soupsieve/__meta__.py, soupsieve/css_match.py, soupsieve/css_parser.py, soupsieve/css_types.py, soupsieve/util.py, tests/test_level3.py, tests/test_level4.py
This is a work in progress. I've just finally come to what I think is an understanding of how this *should* be implemented. The code here *should* work according to my understanding, but I need to finish all the test cases to make sure. Currently, it will only be for HTML. I will have to decipher XML logic for directionality if I want to pursue that.  XML support would be covered under a separate issue.
Closes #36
=> Add :dir() selector for HTML (WIP)

docs/src/markdown/about/changelog.md, docs/src/markdown/api.md, docs/src/markdown/index.md, soupsieve/__init__.py, soupsieve/__meta__.py, soupsieve/css_match.py, tests/test_soupsieve.py
=> Add 'closest' api method

.travis.yml, tox.ini
Add python 3.8 testing. Closes #56.
Ref #54.
=> Test in Python3.8

docs/src/markdown/about/changelog.md, soupsieve/__meta__.py, soupsieve/css_types.py, soupsieve/util.py
=> Import Mapping from collections.abc on Python 3

soupsieve/css_parser.py
=> Better Re pattern for attr values that works with older Python Re

appveyor.yml, tox.ini
Not sure if this fixes anything, but upgrading virtualenv may be fixing the wrong pip issue.  I guess if we get a failure, we'll know it didn't work 🤷‍♂️ .
=> Upgrade virtualenv, tox when setting up Appveyor.

.pyspelling.yml, docs/src/markdown/about/changelog.md, soupsieve/css_types.py, tests/test_soupsieve.py
=> Fix pickle issue

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, soupsieve/css_parser.py
Improve some of the exception messages and fix the reporting of the
character index after a combinator is parsed.
=> Better exception messages

docs/src/markdown/about/changelog.md, soupsieve/css_parser.py, tests/test_level3.py
=> When converting input numbers, use base 10, not base 16

docs/src/markdown/about/changelog.md, soupsieve/css_match.py, tests/test_level2.py, tests/util.py
=> Fix type selector HTML detection

docs/src/markdown/about/changelog.md, soupsieve/css_parser.py, tests/test_level1.py, tests/test_level2.py, tests/test_level3.py, tests/test_level4.py, tests/util.py
=> Test all parsers and fix :disabled and :enabled

docs/src/markdown/index.md, docs/src/markdown/selectors.md
- Update CSS document links.
- Add note about differences in Soup Sieve vs old legacy BS4 select
- Add examples of using Soup Sieve through BS4's API
- Small fixes for some typos
=> Document changes

docs/src/markdown/about/changelog.md, setup.py, soupsieve/__meta__.py
=> Don't install tests when installing soupsieve

docs/src/markdown/about/changelog.md, soupsieve/css_parser.py, tests/test_level1/test_class.py, tests/test_level2/test_attribute.py
=> Null character should translate to REPLACEMENT CHARACTER (U+FFFD)

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, soupsieve/css_parser.py, tests/test_level1/test_class.py
=> Handle escaped EOF edge case

docs/src/markdown/_snippets/links.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/api.md, soupsieve/__init__.py, soupsieve/css_parser.py, soupsieve/util.py, tests/test_api.py
=> Add CSS escape function

docs/src/markdown/about/changelog.md, docs/src/markdown/api.md, soupsieve/__init__.py, soupsieve/css_match.py, tests/test_api.py
=> Deprecate comments and icomments API functions

.travis.yml, docs/src/markdown/about/changelog.md, mkdocs.yml, setup.py, soupsieve/__meta__.py, tox.ini
=> Add Python 3.8 support bump version and fix document site description

docs/src/markdown/about/changelog.md, soupsieve/__init__.py, soupsieve/__meta__.py, soupsieve/css_match.py, soupsieve/util.py, tests/test_api.py
Backing out REVERSE flag for now as it is uncertain what future changes
in relation to iframe we will make, and REVERSE may turn out to be
expensive if we have to account for such things. Rather not add it, and
see down the road that it won't be too bad, then add it now, and find
supporting it would be too painful.
=> Backout REVERSE flag for now

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/faq.md, mkdocs.yml, soupsieve/__meta__.py, tests/test_level4/test_nth_child.py
Fix changelog typo. Add F.A.Q. detailing iframe behavior. Bump version.
=> Prep for 1.9.1 release

.github/labeler.yml, .github/labels.yml, .github/workflows/deploy.yml, .github/workflows/labeler.yml, .github/workflows/newpull.yml, .github/workflows/triage.yml, README.md
Force versions on all actions
Tweak managed labels
Add auto-labeler actions
Remove duplicate link in README
=> Workflow tweaks

docs/src/markdown/about/changelog.md, soupsieve/css_parser.py
Fix corner case with namespace splitting and refactor selector
loading.
=> Fix corner case with namespace splitting and mild refactoring

.github/workflows/deploy.yml, README.md, mkdocs.yml, requirements/docs.txt
Lock to a specific revision of our custom doc plugin, that way we won't
pull a volatile release. The final release of Material isn't too far
away, but we don't want to break between now and then.
=> Fix document building

soupsieve/css_parser.py
=> Fix a typo in NotImplementedError message

.github/workflows/build.yml, .github/workflows/deploy.yml, docs/src/markdown/selectors/index.md
- Fix issues with CI and PY39
- Ensure we are not limiting the document deploy fetch depth so we
can properly take advantage of the git-revision-date-localized
extension in the documents
- Bump default test environment to 3.8
Cloes #201
=> CI updates

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, soupsieve/css_match.py, tests/test_level2/test_attribute.py, tests/test_level3/test_not.py, tox.ini
=> Handle weird attribute inputs

docs/src/markdown/about/changelog.md, soupsieve/__init__.py, soupsieve/__meta__.py, soupsieve/css_types.py
=> Fix issue when a namespace is named 'self'

.github/workflows/build.yml, .github/workflows/deploy.yml
Upgrade action deps as suggested by @cclauss. Closes #222.
=> Update action to setup-python v2

docs/src/markdown/about/changelog.md, soupsieve/__meta__.py, soupsieve/css_parser.py, tests/test_level3/test_attribute.py
=> Ensure attribute selectors match tags that have new lines chars in attr

.pyspelling.yml, tests/test_extra/test_soup_contains.py, tests/test_extra/test_soup_contains_own.py
=> Update tests to account for latest lxml and libxml2 versions

.github/workflows/build.yml, .github/workflows/deploy.yml, docs/src/markdown/about/development.md, hatch_build.py, tox.ini
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
=> Add support for Python 3.11

.github/workflows/build.yml
=> Re-enable windows testing of lxml

docs/src/markdown/about/changelog.md, soupsieve/__meta__.py, soupsieve/css_parser.py, tests/test_level4/test_attribute.py
=> More correct attribute flag syntax

docs/src/markdown/selectors/combinators.md
the selector is wrong, it's same as General sibling combinator.
=> fix Adjacent sibling combinator example
