facelessuser/soupsieve

- .codecov.yml
- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/api.md
- soupsieve/__init__.py
- soupsieve/__meta__.py
- soupsieve/css_parser.py
- soupsieve/util.py
- tests/test_level1.py
- tests/test_level2.py
- tests/test_soupsieve.py
Use iselect and icomments instead as they are shorter and easier to read. Closes #3 .
> Deprecate commentsiter and selectiter

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/css_match.py
- tests/test_bs4_cases.py
In document formats that don't support namespaces, we should not fail the type if namespace doesn't match.
> Fix namespace issue with nth-of-type

- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/about/development.md
- docs/src/markdown/api.md
- docs/src/markdown/selectors.md
- soupsieve/__init__.py
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- soupsieve/util.py
- tests/test_extra.py
- tests/test_level1.py
- tests/test_level2.py
- tests/test_level3.py
- tests/test_level4.py
- tests/test_soupsieve.py
- tests/util.py
CSS selectors should be evaluated with CSS whitespace rules.
CDATA, declarations, and processing instructions should not be
considered in `:empty`.
:contains should only parse CDATA in XML docs. Consider it ws in HTML.
> Whitespace fixes and remove document flags

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- tests/test_soupsieve.py
Also raise NotImplementedError for unsupported pseudo classes.
I knew I was going to find something as soon as I released it....
> Select matches children of a given tag, not the tag itself

- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/about/development.md
- docs/src/markdown/api.md
- docs/src/markdown/selectors.md
- soupsieve/__init__.py
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- soupsieve/util.py
- tests/test_bs4_cases.py
- tests/test_level2.py
- tests/test_soupsieve.py
A couple of small fixes just for polish:
- filter should handle all iterables consistently (no special cases).
- More consistent naming of variables in API and better descriptions in documents.
- Capture pseudo-element pattern so that we can give a better exception.
- Add DEBUG flag for development purposes.
- Track index in selector pattern to bubble up more useful exceptions.
- More accurate exception descriptions.
- Fail for bad input type
- cache no meta language found
> A couple of minor fixes / error handling improvements

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/css_parser.py
- tests/test_level2.py
According to the spec, if the value contains whitespace, or is an empty
string, it should not match anything. Closes #30.
> Fix `[attr~=value]` handling of whitespace

- docs/src/markdown/about/changelog.md
- docs/src/markdown/api.md
- docs/src/markdown/selectors.md
- soupsieve/__init__.py
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- tests/test_level4.py
- tests/util.py
Make CSSMatch take a "scope" for initialization purposes. Calculate
root and scope so that all match calls after will have references to the
current root and/or scope. Use the calculated root and scope variables
to match :root or :scope.
> Add support for :scope

- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/selectors.md
- soupsieve/__meta__.py
- soupsieve/css_parser.py
- tests/test_level2.py
- tests/test_level4.py
Fail for @at-rules
Match nothing for :host, :host(), :host-context, :left, and :right
> Add either failures or match nothing for certain unsupported selectors

- docs/src/markdown/about/changelog.md
- docs/src/markdown/api.md
- docs/src/markdown/index.md
- soupsieve/__init__.py
- soupsieve/css_match.py
- tests/test_soupsieve.py
Adds `select_one` function that returns a single tag or None if the tag is not found. Closes #45.
> Add select_one api function

- soupsieve/css_parser.py
As we are using Unicode regular expressions `\d` probably includes characters we don't want to include. It is better for us to just use `[0-9]`. It's a very minor bug.
> Don't use \d for numbers

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/css_parser.py
- tests/test_level4.py
- tests/test_soupsieve.py
Fix issue with `:has()` selector where a leading combinator can only be
provided in the first selector in a relative selector list.
> Fix issue that prevents using a leading combinator in :has() selector that is not the first selector

- soupsieve/__init__.py
- soupsieve/css_match.py
- soupsieve/util.py
Refactor by splitting element related manipulation to its own mixin class. Also move input validation and parsing to its own mixin. Ensure we are calling the helper methods in the mixin.  This will help a few
areas where we are reusing the same logic over and over and ensure that we are consistent with our logic to prevent breakage in one off locations.
This may allow in the future the ability to derive some of the classes to perform CSS selects on something like etree (or other) objects directly if we feel the need in the future. There is no plan for this, but abstracting things like this will help with maintenance in the future.
> Refactor of match

- docs/src/markdown/about/changelog.md
- docs/src/markdown/api.md
- soupsieve/__meta__.py
- soupsieve/css_match.py
- tests/test_bs4_cases.py
- tests/test_level1.py
- tests/test_level2.py
- tests/test_level3.py
Tag names should be case sensitive for XML. XHTML should be treated like
XML not HTML.
Fixes #95
> Fix case regressions and issues

- .travis.yml
- tests/test_api.py
- tests/test_bs4_cases.py
- tests/test_level2/test_child.py
- tests/test_level3/test_nth_child.py
- tests/test_level4/test_dir.py
- tests/test_level4/test_scope.py
- tests/util.py
- tox.ini
html5lib and lxml are optional bs4 dependencies. If they are not available, test without them, skipping any tests that weren't able to be run.
In Debian, we package separate cPython 2.x and PyPy 2.x stacks. bs4 is available for PyPy in Debian, but html5lib and lxml aren't, yet. Let's just skip these tests when we can't run them, as bs4 does for its own tests.
> Skip tests that require html5lib or lxml when not available

- docs/src/dictionary/en-custom.txt
- soupsieve/__init__.py
- soupsieve/css_parser.py
- soupsieve/util.py
- tests/test_api.py
- tests/test_level1/test_class.py
- tests/test_level1/test_id.py
- tests/test_level1/test_list.py
- tests/test_level1/test_type.py
- tests/test_level2/test_attribute.py
- tests/test_level2/test_child.py
- tests/test_level3/test_nth_child.py
- tests/test_level4/test_attribute.py
- tests/test_level4/test_has.py
- tests/test_level4/test_is.py
Refactored syntax error work done in pull #103 
The big difference here is we take control of the output opposed to relying on `SyntaxError`, which was designed for Python syntax errors, to format it for us. In the future (version 2.0) we will most likely derive from `Exception` instead of `SyntaxError`, as it is probably more appropriate for us to not confuse people by deriving from `SyntaxError`. This will allow us backwards compatibility for exception detection through the 1.0 series.
> @mgedmin better syntax errors

- docs/src/markdown/about/changelog.md
- soupsieve/css_parser.py
- tests/test_extra/test_contains.py
- tests/test_extra/test_custom.py
- tests/test_level1/test_type.py
- tests/test_level2/test_attribute.py
- tests/test_level4/test_lang.py
Allow '--' as a valid identifier or identifier start.
Newlines pattern should treat '\r\n' as a single character, especially
in string escapes: '\\\r\n'.
CSS string patterns should allow escaping newlines.
Closes #93.
> CSS pattern fixes

- docs/src/markdown/about/changelog.md
- docs/src/markdown/api.md
- soupsieve/__init__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- soupsieve/util.py
- tests/test_api.py
- tests/test_extra/test_custom.py
After thinking about things more. If we added variable support in custom selectors we probably don't need a class, we could just do something like `{':--custom(3)': ':is(td:nth-child(3 of $1), $2, $3)'}`. Adding custom functions is probably beyond what we would even do, so limiting this to a dictionary is probably fine. We don't have such support currently, and there is no immediate plan, but this is mainly just thinking about the "maybes" in the future.
Custom selectors, if they were to use variables, they'd also need to be compiled at selector build time as the variables would be unknown.  So we also decided to go with an approach that builds the custom selectors when we need them. Currently, for the simple types of selectors we currently allow, they are cached, but if we allowed …
> Simplify custom API and compile custom selectors "just in time"

- soupsieve/css_parser.py
- soupsieve/util.py
Consolidate pattern context logic to a function that can be used by both
warnings and exceptions. Process all line endings (`\r\n`, `\r`, or
`\n`).
> Add pattern context to quirks warning and handle newlines better

- docs/src/markdown/_snippets/links.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/about/development.md
- docs/src/markdown/selectors.md
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- tests/test_api.py
- tests/test_extra/test_contains.py
This expands the `:contains()` pseudo-class syntax so that it can now accept a comma separated list of text to match instead of just a single text entry to match. Based on the evolution of selectors such as `:lang()`, this seemed like a logical progression for this selector if it had stayed in the official spec.
This pull also ensures that when we are comparing an elements content to multiple text (whether by a list of text or separate instances of contains) that we only acquire the element's text content once instead of for every comparison.
Fixes #115.
> Allow :contains() to have lists of text to match

- docs/src/markdown/about/changelog.md
- soupsieve/css_match.py
- soupsieve/css_parser.py
- tests/test_extra/test_contains.py
- tests/test_level2/test_lang.py
- tests/test_level3/test_root.py
- tests/test_level4/test_default.py
- tests/test_level4/test_dir.py
- tests/test_level4/test_indeterminate.py
- tests/util.py
Ensure that all HTML specific selectors are comparing all related
elements against the XHTML namespace. In HTML parsers that do not
provide an HTML namespace for HTML elements, assume XHTML namespace.
Ensure that :root, :contains(), :lang(), :dir(), :default, and :indeterminate all consider
iframe boundaries and do not evaluate parent or child documents when
determining whether an element matches or not.
When a scoped selector is part of an iframe, :root should match that
scoped element's document root, and not the root of the whle tree.
Reference: #138
> HTML specific selector improvements

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/css_match.py
If an element has that has content we wish to skip, we have to calculate
the last descendant. Usually this is done by descending down the various
`content` members of the tags looking at their last node until we find
one that is not a tag. But we can shortcut this if the element whose
content we wish to skip has a sibling.
> Shortcut to last descendant if available

- docs/src/markdown/about/changelog.md
- soupsieve/css_match.py
- tests/test_level3/test_root.py
A valid root tag should not have sibling tags or HTML content strings.
Doctype, preprocessing strings, and whitespace can be ignored.
Fixes #145
> Add additional validation for :root selectors

- requirements/flake8.txt
- soupsieve/css_match.py
Move a BeautifulSoup specific navigation/access call to _DocumentNav
Rename a couple of classes to private class names
CSSMatch now inherits the _Match and _DocumentNav class in case we ever
want to subclass to support different parsers.
> CSSMatch tweaks

- .travis.yml
- docs/src/markdown/about/changelog.md
- soupsieve/css_parser.py
`[attr!=value]` pattern was mistakenly using `:not([attr|=value])` logic
instead of `:not([attr=value])`
> Fix [attr!=value]

- .travis.yml
- appveyor.yml
- setup.py
- tests/test_level4/test_defined.py
- tests/util.py
It seems that LXML addressed a quirk we had noticed in our tests. Now
it behaves more like we would expect.
> Fix tests for lxml 4.4.0+

- docs/src/dictionary/en-custom.txt
- docs/src/markdown/_snippets/selector_styles.txt
- docs/src/markdown/differences.md
- docs/src/markdown/selectors.md
- soupsieve/__meta__.py
Selector docs now provide better descriptions of selectors and examples.  Links to sites with even more information on a given selector are also provided which should provide even more detailed explanations and more examples.
> Selector doc improvements

- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/selectors.md
- soupsieve/__meta__.py
- soupsieve/css_parser.py
- tests/test_level4/test_lang.py
Recently, it was being discussed on the csswg-drafts repo whether certain languages should be converted to canonical extlang. While I was exploring how we'd possibly go about this, I stumbled on some scenarios related to the starting wildcard in language filters that I had overlooked, and possibly misinterpreted.  I ended up trying a couple implementations in different languages, and concluded that we didn't properly handle `*-subtag` scenarios. Specifically we didn't have it properly select 0 or more matches, and instead it selected 1 or more. This has been fixed.
With that said, there is still questions whether we support `*-*-subtag` properly, or even `subtag-*-*-subtag`. The implementations I tired outside of ours handled this very different. One treated it like ours, which …
> Lang wildcard start

- soupsieve/css_match.py
Case insensitive logic, in relation to CSS or HTML, usually refers to ASCII range of printable characters. CSS tokens, HTML tag names, attribute names, etc. Ensure that we use that logic in all places where appropriate.
In this case that we are fixing, while the case logic is changed, the matching results will remain unchanged. It is ensuring consistency throughout the code as there is currently no issue in the end results.
> Use consistent lower logic in all places

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- tests/test_level3/test_disabled.py
Fix option element related issues in pseudo-classes `:checked` and `:disabled`
- Nothing in the level 4 specifications mentions that `option` elements have to be a child of `select` when they are considered for `:checked`.
- Also, `:disabled`, when applied to `optgroup`, is only supposed to affect the options directly under itself. If you had nested `optgroup` elements, the `option` elements should only be disabled if its closest parent is `disabled`. Grandparents `optgroups` should have no effect.
> Fix option related issues in pseudo-classes :checked and :disabled

- docs/src/markdown/about/changelog.md
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
Browsers never let optgroup get nested as they shuffle elements around
and even strip out tags that don't belong under an optgroup if it is
under a select. For this reason, using the browser as an example is not
always the best unless the tree is also examined and rendering.
Ultimately, we don't need to go out of our way account for bad HTML, and
for the fact that the Python parsers don't quite parse exactly like a
browser, so we will continue to simply match according to the rules.
> Revert :disabled change

- docs/src/markdown/about/changelog.md
- docs/src/markdown/selectors.md
- soupsieve/css_parser.py
- tests/test_level4/test_lang.py
This reverts recent change to `:lang()` that had `*`, when found in the
language range, match 0 or more tags/subtags. `*` in the primary, language
range must match a tag in that range. It is also allowed to match
singletons. Implicit matching between subtags cannot match any
singletons (private include).
It bothered me that some of the other libraries I compared our matching
against matched zero or one, but as those were my only references,
I had decided to go with it. But now that I've found another that goes
along with my same interpretation, I feel more confident continuing
with our current approach. With that said, re-reading the RFC4647
spec, it seems pretty clear that any singleton should be ignored when
doing the implicit matching:
> Else, if the language tag's subtag is a …
> Fix level 4 :lang() wildcard match handling with singletons

- soupsieve/css_match.py
- soupsieve/css_parser.py
- tests/test_level4/test_lang.py
Instead of using regular expression, use the algorithm as described
in RFC4647. This basically pulls over just the logic for the extended filter from #159 .
> Update language filter algorithm

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/util.py
SyntaxError is really used for Python syntax errors. We should not
confuse our selector syntax errors with Python syntax errors.
> SelectorSyntaxError is now derived from Exception

- soupsieve/util.py
Fixes https://github.com/facelessuser/soupsieve/issues/184
Removing this line removes the only reference to `__file__`, which
allows tools like pyoxidizer to create standalone binaries that depend
on this package. See also:
https://github.com/indygreg/PyOxidizer/issues/69
> Remove unused variable MODULE

- soupsieve/util.py
`lower()` is a hot function that seems to be usually called with a very few different parameters, so using an LRU cache makes it much more efficient. (The maxsize parameter could be tweaked, maybe?)
Closes #190
> perf: Annotate soupsieve.util.lower() with LRU cache

- soupsieve/css_match.py
In my app, this makes `is_tag` (the third hottest function according to profiling) about 24% faster:
func | ncalls | time | owntime
---- | ----- | ---- | --------
master/is_tag | 2054073 | 1566 | 1179
perf-istag/is_tag | 2054073 | 1191 | 775
I assume unpacking all of the classes from `bs4` might make things a little faster still, but it's probably not worth the mess?
> perf: don't import bs4 in every `is_...` function

- docs/src/markdown/selectors/pseudo-classes.md
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- tests/test_api.py
- tests/test_extra/test_soup_contains.py
- tests/test_extra/test_soup_contains_own.py
- Rename :contains() to :-soup-contains().
- Allow usage of :contains() but mark it as deprecated and instruct
users to switch over to :-soup-contains().
- Add :-soup-contains-own which is like contains, but adds the
restriction that the text nodes must be under the element under
evaluation.
Closes #200
This is under evaluation and may or may not be merged.
> :-soup-contains-own (based on #200 by @sm-ghavami)

- .github/workflows/deploy.yml
- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/selectors/pseudo-classes.md
- soupsieve/__meta__.py
- soupsieve/css_parser.py
I'm really glad they dropped <link> as it didn't make much sense.
> Update :any-link and :link to reflect recent level 4 CSS selector change

- .gitignore
- docs/src/markdown/about/changelog.md
- mkdocs.yml
- requirements/docs.txt
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- tests/test_level3/test_not.py
- tests/test_level4/test_has.py
- tests/test_level4/test_is.py
> Allow `:is()`, `:has()`, and `:where()` to forgive empty slots

- docs/src/markdown/about/changelog.md
- soupsieve/__meta__.py
- soupsieve/css_parser.py
- tests/test_level4/test_has.py
- tests/test_level4/test_nth_child.py
- tests/test_level4/test_nth_last_child.py
Recent CSS spec updated :has() to not be forgiving. This is to address JQuery issues. With that said, we do not offer true forgiving anyways, just comma forgiveness. As CSS will not be allowing forgiveness for relative selectors, we will not continue supporting it.
> :has() should not have any kind of forgiving behavior

- .github/workflows/build.yml
- hatch_build.py
- pyproject.toml
- soupsieve/__init__.py
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- soupsieve/css_types.py
- soupsieve/pretty.py
- soupsieve/util.py
- tests/test_api.py
- tests/test_level4/test_dir.py
- tests/util.py
- tox.ini
The [Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
See also https://dev.to/hugovk/help-test-python-312-beta-1508/
Also drop support for EOL Python 3.7 https://devguide.python.org/versions/ and upgrade Python syntax with `pyupgrade --py38-plus`.
> Add support for Python 3.12 and drop EOL 3.7

- LICENSE.md
- README.md
- docs/src/markdown/about/changelog.md
- docs/src/markdown/selectors/pseudo-classes.md
- mkdocs.yml
- pyproject.toml
- soupsieve/__init__.py
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- tests/test_nesting_1/__init__.py
- tests/test_nesting_1/test_amp.py
When used outside the context of nesting, ampersand is treated as the scoping root.
> Add support for nesting ampersand

- docs/src/markdown/about/changelog.md
- soupsieve/css_parser.py
- tests/test_level1/test_pseudo_class.py
When encountering a pseudo-class that is unrecognized, we should not state it is "unsupported" a it may be entirely invalid. While there are some pseudo-classes that are valid but not supported, the status of such things can change all the time and our internal list may become outdated.
Additionally, sometimes users trying to incorrectly specify tags with namespaces can trigger this message as they may assume that because a namespace is declared in their document as `ns:element` that they can do this in CSS as well. This specific case is not easily detectable for us as we generically parse the syntax, not the intent of the syntax.
To clear up confusion, be more specific and simply state that anytime a pseudo-class is not recognized by soupsieve that it is either invalid or not …
> Improve pseudo-class error message

- docs/src/markdown/about/changelog.md
- pyproject.toml
- soupsieve/__init__.py
- soupsieve/__meta__.py
- soupsieve/css_match.py
> Fix some typing issues revealed with latest BS4

- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/selectors/pseudo-classes.md
- docs/src/markdown/selectors/unsupported.md
- mkdocs.yml
- pyproject.toml
- soupsieve/__meta__.py
- soupsieve/css_match.py
- soupsieve/css_parser.py
- tests/test_level4/test_muted.py
- tests/test_level4/test_open.py
- Add `:open` and `:muted`
- Recognize `:autofill`, `:buffering`, `:fullscreen`, `:picture-in-picture`, `:popover-open`, `:seeking`, `:stalled`, and `:volume-locked`.
- Move various existing pseudo-classes out of experimental status.
> Add new selectors and move some existing selectors out of experimental
